services:
  serv-mech-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # expose:
    #   - "5432"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - mech_db_data:/var/lib/postgresql/data
    networks:
      - mechanic-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  serv-mech-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - mechanic-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  serv-mech-api:
    image: sebastiandevjs/mech-api:1.0.0
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      serv-mech-db:
        condition: service_healthy
      serv-mech-redis:
        condition: service_healthy
    networks:
      - mechanic-net
    healthcheck:
      test:
        [
          "CMD", "python", "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/system/health', timeout=5).read()"
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s

  serv-mech-worker:
    image: sebastiandevjs/mech-api:1.0.0  # misma imagen que api, distinto command
    restart: unless-stopped
    command: ["/app/scripts/start_worker.sh"]
    env_file:
      - .env
    volumes:
      - storage_data:/app/storage
    depends_on:
      serv-mech-db:
        condition: service_healthy
      serv-mech-redis:
        condition: service_healthy
    networks:
      - mechanic-net

  serv-mech-web:
    image: sebastiandevjs/mech-web:1.0.0
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - serv-mech-api
    networks:
      - mechanic-net

  serv-mech-flutter-web:
    image: sebastiandevjs/mech-flutter-web:1.0.0
    restart: unless-stopped
    depends_on:
      - serv-mech-api
    networks:
      - mechanic-net

  serv-nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - serv-mech-web
      - serv-mech-api
      - serv-mech-flutter-web
    networks:
      - mechanic-net

volumes:
  mech_db_data:
  redis_data:
  storage_data:

networks:
  mechanic-net:
    name: mechanic-system_mechanic-net
    driver: bridge