ROLE_CLIENT = "CLIENT"
ROLE_PROVIDER_ADMIN = "PROVIDER_ADMIN"
ROLE_TECHNICIAN = "TECHNICIAN"
ROLE_PLATFORM_ADMIN = "PLATFORM_ADMIN"

INITIAL_SYSTEM_ROLE_CODES = (
    ROLE_CLIENT,
    ROLE_PROVIDER_ADMIN,
    ROLE_TECHNICIAN,
    ROLE_PLATFORM_ADMIN,
)

ACCOUNT_TYPE_CLIENT = "CLIENT"
ACCOUNT_TYPE_INDEPENDENT_MECHANIC = "INDEPENDENT_MECHANIC"
ACCOUNT_TYPE_WORKSHOP = "WORKSHOP"

PUBLIC_ACCOUNT_TYPES = (
    ACCOUNT_TYPE_CLIENT,
    ACCOUNT_TYPE_INDEPENDENT_MECHANIC,
    ACCOUNT_TYPE_WORKSHOP,
)

PROVIDER_TYPE_INDEPENDENT_MECHANIC = "INDEPENDENT_MECHANIC"
PROVIDER_TYPE_WORKSHOP = "WORKSHOP"

PUBLIC_PROVIDER_TYPES = (
    PROVIDER_TYPE_INDEPENDENT_MECHANIC,
    PROVIDER_TYPE_WORKSHOP,
)

VEHICLE_TYPE_CAR = "CAR"
VEHICLE_TYPE_MOTORCYCLE = "MOTORCYCLE"
VEHICLE_TYPE_TRUCK = "TRUCK"
VEHICLE_TYPE_VAN = "VAN"
VEHICLE_TYPE_OTHER = "OTHER"

INCIDENT_STATUS_PENDING = "PENDING"
INCIDENT_STATUS_IN_REVIEW = "IN_REVIEW"
INCIDENT_STATUS_PUBLISHED = "PUBLISHED"
INCIDENT_STATUS_ASSIGNED = "ASSIGNED"
INCIDENT_STATUS_EN_ROUTE = "EN_ROUTE"
INCIDENT_STATUS_ON_SITE = "ON_SITE"
INCIDENT_STATUS_IN_PROGRESS = "IN_PROGRESS"
INCIDENT_STATUS_COMPLETED = "COMPLETED"
INCIDENT_STATUS_CANCELLED = "CANCELLED"

INCIDENT_PRIORITY_LOW = "LOW"
INCIDENT_PRIORITY_MEDIUM = "MEDIUM"
INCIDENT_PRIORITY_HIGH = "HIGH"
INCIDENT_PRIORITY_CRITICAL = "CRITICAL"

INCIDENT_CATEGORY_BATTERY = "BATTERY"
INCIDENT_CATEGORY_TIRE = "TIRE"
INCIDENT_CATEGORY_ACCIDENT = "ACCIDENT"
INCIDENT_CATEGORY_ENGINE = "ENGINE"
INCIDENT_CATEGORY_LOCKOUT = "LOCKOUT"
INCIDENT_CATEGORY_OVERHEATING = "OVERHEATING"
INCIDENT_CATEGORY_OTHER = "OTHER"
INCIDENT_CATEGORY_UNCERTAIN = "UNCERTAIN"

PUBLIC_INCIDENT_CATEGORIES = (
    INCIDENT_CATEGORY_BATTERY,
    INCIDENT_CATEGORY_TIRE,
    INCIDENT_CATEGORY_ACCIDENT,
    INCIDENT_CATEGORY_ENGINE,
    INCIDENT_CATEGORY_LOCKOUT,
    INCIDENT_CATEGORY_OVERHEATING,
    INCIDENT_CATEGORY_OTHER,
    INCIDENT_CATEGORY_UNCERTAIN,
)

SERVICE_CODE_TOWING = "TOWING"
SERVICE_CODE_BATTERY_JUMPSTART = "BATTERY_JUMPSTART"
SERVICE_CODE_TIRE_CHANGE = "TIRE_CHANGE"
SERVICE_CODE_LOCKOUT_ASSISTANCE = "LOCKOUT_ASSISTANCE"
SERVICE_CODE_ENGINE_DIAGNOSTIC = "ENGINE_DIAGNOSTIC"
SERVICE_CODE_OVERHEATING_ASSISTANCE = "OVERHEATING_ASSISTANCE"
SERVICE_CODE_ACCIDENT_SUPPORT = "ACCIDENT_SUPPORT"

INITIAL_SERVICE_CATALOG_ITEMS = (
    {
        "code": SERVICE_CODE_TOWING,
        "category": INCIDENT_CATEGORY_ACCIDENT,
        "title": "Servicio de grúa",
        "description": "Traslado del vehículo cuando no puede circular o requiere remolque.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 10,
    },
    {
        "code": SERVICE_CODE_BATTERY_JUMPSTART,
        "category": INCIDENT_CATEGORY_BATTERY,
        "title": "Auxilio de batería",
        "description": "Paso de corriente, revisión básica o apoyo por batería descargada.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 20,
    },
    {
        "code": SERVICE_CODE_TIRE_CHANGE,
        "category": INCIDENT_CATEGORY_TIRE,
        "title": "Cambio o auxilio de llanta",
        "description": "Cambio de llanta, apoyo por pinchazo o revisión rápida en carretera.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 30,
    },
    {
        "code": SERVICE_CODE_LOCKOUT_ASSISTANCE,
        "category": INCIDENT_CATEGORY_LOCKOUT,
        "title": "Apertura por llave encerrada",
        "description": "Asistencia para apertura del vehículo por bloqueo o llave olvidada.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 40,
    },
    {
        "code": SERVICE_CODE_ENGINE_DIAGNOSTIC,
        "category": INCIDENT_CATEGORY_ENGINE,
        "title": "Diagnóstico mecánico básico",
        "description": "Evaluación inicial de fallas mecánicas o del motor en sitio o taller.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 50,
    },
    {
        "code": SERVICE_CODE_OVERHEATING_ASSISTANCE,
        "category": INCIDENT_CATEGORY_OVERHEATING,
        "title": "Auxilio por sobrecalentamiento",
        "description": "Atención preliminar para vehículos detenidos por calentamiento excesivo.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 60,
    },
    {
        "code": SERVICE_CODE_ACCIDENT_SUPPORT,
        "category": INCIDENT_CATEGORY_ACCIDENT,
        "title": "Atención inicial por choque leve",
        "description": "Inspección preliminar del daño visible y definición del tipo de auxilio requerido.",
        "supports_mobile_service": True,
        "supports_emergency_service": True,
        "sort_order": 70,
    },
)

EVIDENCE_TYPE_IMAGE = "IMAGE"
EVIDENCE_TYPE_AUDIO = "AUDIO"
EVIDENCE_TYPE_TEXT = "TEXT"

PROCESSING_STATUS_NOT_REQUESTED = "NOT_REQUESTED"
PROCESSING_STATUS_PENDING = "PENDING"
PROCESSING_STATUS_RUNNING = "RUNNING"
PROCESSING_STATUS_SUCCEEDED = "SUCCEEDED"
PROCESSING_STATUS_FAILED = "FAILED"

ASSIGNMENT_CANDIDATE_STATUS_AVAILABLE = "AVAILABLE"
ASSIGNMENT_CANDIDATE_STATUS_ACCEPTED = "ACCEPTED"
ASSIGNMENT_CANDIDATE_STATUS_REJECTED = "REJECTED"
ASSIGNMENT_CANDIDATE_STATUS_EXPIRED = "EXPIRED"

DISPATCH_MODE_PROVIDER_SELF = "PROVIDER_SELF"
DISPATCH_MODE_TECHNICIAN = "TECHNICIAN"

TRACKING_SOURCE_PROVIDER_SELF = "PROVIDER_SELF"
TRACKING_SOURCE_TECHNICIAN = "TECHNICIAN"

INCIDENT_OPERATION_EVENT_DISPATCHED = "DISPATCHED"
INCIDENT_OPERATION_EVENT_ARRIVED_ON_SITE = "ARRIVED_ON_SITE"
INCIDENT_OPERATION_EVENT_SERVICE_STARTED = "SERVICE_STARTED"
INCIDENT_OPERATION_EVENT_SERVICE_COMPLETED = "SERVICE_COMPLETED"
INCIDENT_OPERATION_EVENT_SERVICE_CANCELLED = "SERVICE_CANCELLED"

BACKGROUND_JOB_STATUS_PENDING = "PENDING"
BACKGROUND_JOB_STATUS_RUNNING = "RUNNING"
BACKGROUND_JOB_STATUS_SUCCEEDED = "SUCCEEDED"
BACKGROUND_JOB_STATUS_FAILED = "FAILED"

BACKGROUND_JOB_TYPE_DEMO = "DEMO"
BACKGROUND_JOB_TYPE_AUDIO_TRANSCRIPTION = "AUDIO_TRANSCRIPTION"
BACKGROUND_JOB_TYPE_IMAGE_ANALYSIS = "IMAGE_ANALYSIS"
BACKGROUND_JOB_TYPE_INCIDENT_SUMMARY = "INCIDENT_SUMMARY"

CELERY_QUEUE_DEFAULT = "default"
CELERY_QUEUE_AUDIO = "audio"
CELERY_QUEUE_IMAGE = "image"
CELERY_QUEUE_SUMMARY = "summary"
CELERY_QUEUE_PUSH = "push"


BACKGROUND_JOB_TYPE_PUSH_NOTIFICATION = "PUSH_NOTIFICATION"

DEVICE_PLATFORM_ANDROID = "ANDROID"
DEVICE_PLATFORM_IOS = "IOS"
DEVICE_PLATFORM_WEB = "WEB"

PUSH_DELIVERY_STATUS_PENDING = "PENDING"
PUSH_DELIVERY_STATUS_RUNNING = "RUNNING"
PUSH_DELIVERY_STATUS_SUCCEEDED = "SUCCEEDED"
PUSH_DELIVERY_STATUS_FAILED = "FAILED"

PUSH_EVENT_NEW_ASSIGNMENT_AVAILABLE = "NEW_ASSIGNMENT_AVAILABLE"
PUSH_EVENT_INCIDENT_ACCEPTED = "INCIDENT_ACCEPTED"
PUSH_EVENT_TECHNICIAN_ASSIGNED = "TECHNICIAN_ASSIGNED"
PUSH_EVENT_PROVIDER_EN_ROUTE = "PROVIDER_EN_ROUTE"
PUSH_EVENT_PROVIDER_ARRIVED = "PROVIDER_ARRIVED"
PUSH_EVENT_INCIDENT_CANCELLED = "INCIDENT_CANCELLED"
PUSH_EVENT_INCIDENT_COMPLETED = "INCIDENT_COMPLETED"
PUSH_EVENT_TEST = "TEST"

PUBLIC_DEVICE_PLATFORMS = (
    DEVICE_PLATFORM_ANDROID,
    DEVICE_PLATFORM_IOS,
    DEVICE_PLATFORM_WEB,
)


DEFAULT_CURRENCY_CODE = "BOB"
DEFAULT_PLATFORM_COMMISSION_RATE = 0.10

PAYMENT_STATUS_PENDING_PRICING = "PENDING_PRICING"
PAYMENT_STATUS_ESTIMATED = "ESTIMATED"
PAYMENT_STATUS_PENDING_PAYMENT = "PENDING_PAYMENT"
PAYMENT_STATUS_PAID = "PAID"
PAYMENT_STATUS_CANCELLED = "CANCELLED"

PAYMENT_METHOD_CASH = "CASH"
PAYMENT_METHOD_QR = "QR"
PAYMENT_METHOD_GATEWAY = "GATEWAY"
PAYMENT_METHOD_TRANSFER = "TRANSFER"
PAYMENT_METHOD_CARD = "CARD"

PUBLIC_PAYMENT_METHODS = (
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_QR,
    PAYMENT_METHOD_GATEWAY,
    PAYMENT_METHOD_TRANSFER,
    PAYMENT_METHOD_CARD,
)


PLAN_BILLING_PERIOD_MONTHLY = "MONTHLY"
PLAN_BILLING_PERIOD_ANNUAL = "ANNUAL"

PLAN_COVERAGE_TYPE_FIXED_AMOUNT = "FIXED_AMOUNT"
PLAN_COVERAGE_TYPE_PERCENTAGE = "PERCENTAGE"
PLAN_COVERAGE_TYPE_FULL = "FULL"

SUBSCRIPTION_STATUS_ACTIVE = "ACTIVE"
SUBSCRIPTION_STATUS_CANCELLED = "CANCELLED"
SUBSCRIPTION_STATUS_EXPIRED = "EXPIRED"

SUBSCRIPTION_APPLICATION_STATUS_APPLIED = "APPLIED"
SUBSCRIPTION_APPLICATION_STATUS_VOIDED = "VOIDED"



AUDIT_SCOPE_HTTP = "HTTP"
AUDIT_SCOPE_DOMAIN = "DOMAIN"

AUDIT_OUTCOME_SUCCESS = "SUCCESS"
AUDIT_OUTCOME_ERROR = "ERROR"

AUDIT_EVENT_HTTP_REQUEST = "HTTP_REQUEST"
AUDIT_EVENT_INCIDENT_PUBLISHED = "INCIDENT_PUBLISHED"
AUDIT_EVENT_INCIDENT_ACCEPTED = "INCIDENT_ACCEPTED"
AUDIT_EVENT_INCIDENT_DISPATCHED = "INCIDENT_DISPATCHED"
AUDIT_EVENT_INCIDENT_ARRIVED = "INCIDENT_ARRIVED"
AUDIT_EVENT_INCIDENT_COMPLETED = "INCIDENT_COMPLETED"
AUDIT_EVENT_INCIDENT_CANCELLED = "INCIDENT_CANCELLED"
AUDIT_EVENT_BILLING_ESTIMATED = "BILLING_ESTIMATED"
AUDIT_EVENT_BILLING_FINALIZED = "BILLING_FINALIZED"
AUDIT_EVENT_PAYMENT_MARKED_PAID = "PAYMENT_MARKED_PAID"
AUDIT_EVENT_SUBSCRIPTION_PLAN_CREATED = "SUBSCRIPTION_PLAN_CREATED"
AUDIT_EVENT_CLIENT_SUBSCRIBED_TO_PLAN = "CLIENT_SUBSCRIBED_TO_PLAN"
AUDIT_EVENT_COVERAGE_APPLIED = "COVERAGE_APPLIED"
