FROM python:3.12-slim

# Prevents Python from generating .pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Ensures logs are shown immediately in Docker.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# System dependencies commonly needed for PostgreSQL drivers
# and some Python packages with native extensions.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#RUN chmod +x /app/scripts/start.sh && chmod +x /app/scripts/start_worker.sh

RUN sed -i 's/\r$//' /app/scripts/start.sh \
    && sed -i 's/\r$//' /app/scripts/start_worker.sh \
    && chmod +x /app/scripts/start.sh /app/scripts/start_worker.sh

EXPOSE 8000

CMD ["/app/scripts/start.sh"]
