server:
  host: "localhost"
  port: 5200
  # https: # esto hacer despues
  #   cert-path: "/path/to/cert.pem" # Path <string> to your TLS certificate
  #   cert-key-path: "/path/to/key.pem" # Path <string> to TLS certificate key
  proxy:
    - target: "http://localhost:8000/" # Base URL <string> of your backend
      prefix: "/api/" # Path <string>